### ISSUE TITLE
calling from package.json

### ISSUE THREAD

**Issue by idkjs** [ulrikstrid/reenv#21]
I am trying to get reenv to run my graphql introspection command.

I cant seem to call it from the `package.json` script and then pass the value to the command.

Some of the things I have tried.

This works but I can't seem to get past it:

```sh
❯ reenv -e .env  printenv REACT_APP_SERVER_URL 
http://localhost:4000/graphql
```

These doesn't work:

```sh
> reenv -e .env get-graphql-schema $REACT_APP_SERVER_URL -j > graphql_schema.json

reenv: unknown option `-j'.
```

```sh
❯ reenv -e .env npx get-graphql-schema $REACT_APP_SERVER_URL -j
reenv: unknown option `-j'.
Usage: reenv [OPTION]... COMMAND [ARGS]...
Try `reenv --help' for more information.
```

The examples not using `reenv` work.

```json
{
"get-schema-url": "reenv -e .env printenv REACT_APP_SERVER_URL",
    "get-schema-url-flag": "reenv -e .env -- ls printenv REACT_APP_SERVER_URL",
    "get-schema": "ENDPOINT_URL=$(npm run get-schema-url) get-graphql-schema ENDPOINT_URL -j > graphql_schema.json",
    "introspection-reenv": "get-graphql-schema $(npm run get-schema-url) -j > graphql_schema.json",
    "introspection": "get-graphql-schema http://localhost:4000/graphql -j > graphql_schema.json",
    "introspection:gql": "get-graphql-schema http://localhost:4000/graphql > schema.graphql"
  },
```

Thank you, sir.

**Comment by ulrikstrid** [comment]
Hello, could you try using this command: `reenv -e .env -- printenv REACT_APP_SERVER_URL`?

**Comment by idkjs** [comment]
That gets you the value as a scripts command. How do you pass it to the next command? It looks like `get-graphql-schema` is getting called but not registering the url for some reason.

```sh
# ./.env
REACT_APP_SERVER_URL="http://localhost:4000/graphql"
REACT_APP_TEST=http://localhost:4000/graphql
```

```json
# package.json scripts
  	"reenv-test": "reenv -e .env -- printenv REACT_APP_TEST",
	"reenv-test2": "reenv -e .env -- get-graphql-schema REACT_APP_TEST",
```
....
```sh
~/Github/WhatsApp-Clone-Reason/client master*
❯ npm run reenv-test 

> whats-app-reason@0.1.0 reenv-test /Users/mandalarian/Github/WhatsApp-Clone-Reason/client
> reenv -e .env -- printenv REACT_APP_TEST

http://localhost:4000/graphql

❯ npm run reenv-test2

> whats-app-reason@0.1.0 reenv-test2 /Users/mandalarian/Github/WhatsApp-Clone-Reason/client
> reenv -e .env -- get-graphql-schema REACT_APP_TEST

TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/mandalarian/Github/WhatsApp-Clone-Reason/client/node_modules/node-fetch/lib/index.js:1299:9)
    at /Users/mandalarian/Github/WhatsApp-Clone-Reason/client/node_modules/node-fetch/lib/index.js:1404:19
    at new Promise (<anonymous>)
    at Function.fetch [as default] (/Users/mandalarian/Github/WhatsApp-Clone-Reason/client/node_modules/node-fetch/lib/index.js:1401:9)
    at /Users/mandalarian/Github/WhatsApp-Clone-Reason/client/node_modules/get-graphql-schema/dist/index.js:73:62
    at step (/Users/mandalarian/Github/WhatsApp-Clone-Reason/client/node_modules/get-graphql-schema/dist/index.js:33:23)
    at Object.next (/Users/mandalarian/Github/WhatsApp-Clone-Reason/client/node_modules/get-graphql-schema/dist/index.js:14:53)
    at /Users/mandalarian/Github/WhatsApp-Clone-Reason/client/node_modules/get-graphql-schema/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mandalarian/Github/WhatsApp-Clone-Reason/client/node_modules/get-graphql-schema/dist/index.js:4:12)

~/Github/WhatsApp-Clone-Reason/client master*
❯ 
```

**Comment by ulrikstrid** [comment]
So `reenv` just puts things in the environment for you. So `printenv` works because that's exactly what it does.
To make the second usecase work you have to make `get-graphql-schema` read a environment variable instead.
